name: Test for Windows

on:
  - pull_request
  - push

# concurrency:
#   group: ${{ github.workflow }}-${{ (github.ref_name == 'main' && github.run_id) || format('{0}-{1}', github.actor, github.head_ref || github.ref_name) }}
#   cancel-in-progress: true

env:
  YARN_VERSION: '^1.22.22'

jobs:
  win-test:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '^18.20.4'
          - '20.17.0'
          - '^22.8.0'
        include:
          - node-version: '^18.20.4'
            force: true

    steps:
      # - name: Output concurrency group
      #   run: echo "${{ github.workflow }}-${{ (github.ref_name == 'main' && github.run_id) || format('{0}-{1}', github.actor, github.head_ref || github.ref_name) }}"

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile ${{ matrix.force && '--ignore-engines' || '' }}

      # Retry tests up to 3 times due to flaky tests on Windows CI
      # https://stackoverflow.com/a/59365905
      - name: Jest
        env:
          CI: true
        run: >-
          yarn test:coverage --ci -i --reporters=default --reporters=jest-junit --forceExit ||
          yarn test:coverage --ci -i --reporters=default --reporters=jest-junit --forceExit --no-cache ||
          yarn test:coverage --ci -i --reporters=default --reporters=jest-junit --forceExit --no-cache

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: windows
