name: Test for Windows

on:
  - pull_request
  - push

# concurrency:
#   group: ${{ github.workflow }}-${{ (github.ref_name == 'main' && github.run_id) || format('{0}-{1}', github.actor, github.head_ref || github.ref_name) }}
#   cancel-in-progress: true

jobs:
  win-test:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - '^18.20.5'
          - '^20.18.1'
          - '22.12.0'

    steps:
      # - name: Output concurrency group
      #   run: echo "${{ github.workflow }}-${{ (github.ref_name == 'main' && github.run_id) || format('{0}-{1}', github.actor, github.head_ref || github.ref_name) }}"

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npx patch-package

      # Retry tests up to 3 times due to flaky tests on Windows CI
      # https://stackoverflow.com/a/59365905
      - name: Jest
        env:
          MARP_TEST_CI: 1
        run: >-
          npm run test:coverage -- --ci --reporters=default --reporters=jest-junit ||
          npm run test:coverage -- --ci -i --reporters=default --reporters=jest-junit --forceExit --no-cache ||
          npm run test:coverage -- --ci -i --reporters=default --reporters=jest-junit --forceExit --no-cache ||
          npm run test:coverage -- --ci -i --reporters=default --reporters=jest-junit --forceExit --no-cache

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: windows
